# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    # Injeta a API Key do arquivo .env para dentro do contêiner
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    # ADICIONADO: Mantém o contêiner rodando de forma interativa
    stdin_open: true # Mantém o STDIN aberto para entrada de dados (input)
    tty: true        # Aloca um pseudo-TTY, necessário para interatividade