# docker-compose.yml

version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    # Injeta a API Key do arquivo .env para dentro do contêiner
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}